field: 5fbc6670-3580-4027-9a14-5874fae115f2 # ContentBlocks
fieldLayouts:
  872ac680-08c6-401d-ace2-7ac2b2d7a792:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3242ce21-a2d5-4515-975c-9f62c3b3bc94 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae063515-530c-419e-8d83-2cbe872a74ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1f9ae46-b038-4ef8-9ca3-0da789b00ec0 # Title visible
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f40233f-b966-41cb-a31c-e6aaccde0613
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbf5ab16-2093-4969-a1fb-31f4301e34e2 # Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e27fc26-1e5b-4055-8e45-d8c531d87da6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 771b630c-54d8-4fa2-86cf-d06a143f1fe6 # Text size
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14260a97-b3ec-4017-b27f-f2bf5da5f910
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc07a86b-56f8-41ae-b70b-4ca3e53f083e # Text position
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb61239b-36d3-46ad-956d-a854bc24712e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 323d89d6-2947-454b-b2eb-b9406ec41ba1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 399fac35-304c-478e-ad8d-9fffe3203848
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3275a38-d1a4-47ce-b102-80e865f42c7d
        userCondition: null
fields:
  323d89d6-2947-454b-b2eb-b9406ec41ba1: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:7c18c50e-f4ec-49f9-97b8-d29a9e74fb92' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:7c18c50e-f4ec-49f9-97b8-d29a9e74fb92' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  771b630c-54d8-4fa2-86cf-d06a143f1fe6: # Text size
    columnSuffix: qseyoyuq
    contentColumnType: string
    fieldGroup: null
    handle: textSize
    instructions: null
    name: 'Text size'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 1/3
            -
              - value
              - one-third
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2/3
            -
              - value
              - two-third
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/2
            -
              - value
              - half
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  3242ce21-a2d5-4515-975c-9f62c3b3bc94: # Title
    columnSuffix: lfojxibp
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a1f9ae46-b038-4ef8-9ca3-0da789b00ec0: # Title visible
    columnSuffix: vwgcshxg
    contentColumnType: boolean
    fieldGroup: null
    handle: titleVisible
    instructions: null
    name: 'Title visible'
    searchable: false
    settings:
      default: true
      offLabel: Hidden
      onLabel: Visible
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  dbf5ab16-2093-4969-a1fb-31f4301e34e2: # Content
    columnSuffix: mfxstthg
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  dc07a86b-56f8-41ae-b70b-4ca3e53f083e: # Text position
    columnSuffix: bjsmpqko
    contentColumnType: string
    fieldGroup: null
    handle: textPosition
    instructions: null
    name: 'Text position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - First
            -
              - value
              - first
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Last
            -
              - value
              - last
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: richText
name: RichText
sortOrder: 1
