# https://www.webstoemp.com/blog/github-actions-deploy-craftcms/
# https://swharden.com/blog/2022-04-24-github-actions-ftp/

name: 🚀 FTP Deploy
on: [push, workflow_dispatch]

env:
  APP_PATH: ~/craft/lilwiz
  WEB_PATH: ~/www/lilwiz
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      # Setup container with private SSH Key (used by rsync)
      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Install PHP dependencies
      # - name: Composer install
      #  run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      # RSYNC
      # - rsync [options] ~/localdir ssh_user@ssh_host:destination_directory
      # - exclude web/uploads is there to avoid deleting user uploaded files w/ --delete-after
      # - StrictHostKeyChecking=no will automatically add new host keys to the user known hosts files.
      - name: Deploy craft project with rsync
        run: |
          rsync -azh --delete-after --exclude={"/.env","/.ddev/","/web/","/node_modules/","/.git/","/.github/"} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.APP_PATH}}

      - name: Deploy web files with rsync
        run: |
          rsync -azh --delete-after --exclude={"/index.php"} -e "ssh -o StrictHostKeyChecking=no" ./web ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.WEB_PATH}}


      # execute Craft commands on remote server
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.APP_PATH }}
            mkdir -p storage
            chmod a+x craft
            php craft db/backup
            php craft migrate/all
            php craft project-config/apply
            php craft clear-caches/all
